name: Build Froggi (macOS)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: dev  # Checkout the dev branch

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Ensure C build tools are installed
      run: |
        if ! xcode-select --install 2>/dev/null; then
          echo "Xcode command line tools are already installed"
        fi

    - name: Build Froggi
      run: |
        cargo build --release

    - name: Archive compiled binary
      run: |
        mkdir -p build
        mv target/release/froggi build/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: froggi-macos-build
        path: build/
